name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.*.x"
    paths:
      - .github/workflows/coding-standards.yml
      - composer.*
      - phpcs.xml.dist
      - src/**
      - tests/**
  push:
    branches:
      - "*.*.x"
    paths:
      - .github/workflows/coding-standards.yml
      - composer.*
      - phpcs.xml.dist
      - src/**
      - tests/**

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: ${{ matrix.php-versions }}
          tools: "cs2pr"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"

      - name: "Run PHPCS"
        run: "composer lint-check -- -q --no-colors --report=checkstyle | cs2pr"