name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.*.x"
    paths:
      - .github/workflows/static-analysis.yml
      - psalm.xml.dist
      - src/**
      - tests/**

  push:
    branches:
      - "*.*.x"
    paths:
      - .github/workflows/static-analysis.yml
      - psalm.xml.dist
      - src/**
      - tests/**

jobs:
  static-analysis:
    name: "Static Analysis"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: ${{ matrix.php-versions }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"

      - name: "Run Psalm"
        run: "composer static-analysis"